Resources:
  StrateyTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.var.strategyTable}
      KeySchema:
        - KeyType: 'HASH'
          AttributeName: 'id'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      BillingMode: PAY_PER_REQUEST