service: aws-service
frameworkVersion: '2'

custom: ${file(./serverless.shared.template.yml):custom}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, env:STAGE}
  lambdaHashingVersion: 20201221
  region: ap-southeast-2
  environment: ${file(./serverless.shared.template.yml):environment} 
  iam:
    deploymentRole: ${self:custom.var.cfnRole}
    
package:
  individually: true

functions:
  hello:
    handler: src/function/hello.handler
    events:
      - http:
          path: hello 
          method: get


plugins:
  - serverless-webpack